"""
02: Run Pywr-DRB simulations for all Sobol samples.

This script runs Pywr-DRB simulations for each parameter sample.
Supports both MPI parallel execution (for HPC) and serial execution.

Uses the TRIMMED MODEL by default for faster runtime (~50-70% speedup).
The trimmed model requires pre-simulated releases generated by
00_generate_presimulated_releases.py.

Usage:
    python 02_run_simulations.py
    mpiexec -n 16 python 02_run_simulations.py
"""

import sys
from pathlib import Path

# Add methods to path
sys.path.insert(0, str(Path(__file__).parent))

from config import (
    START_DATE,
    END_DATE,
    INFLOW_TYPE,
    SIMULATIONS_DIR,
    USE_TRIMMED_MODEL,
    PRESIM_FILE,
)
from methods.sampling import load_samples
from methods.simulation import (
    run_parallel_simulations_mpi,
    run_simulations_serial,
    save_simulation_results,
    verify_simulation_outputs,
    MPI_AVAILABLE
)

# =============================================================================
# SCRIPT SETTINGS (modify these as needed)
# =============================================================================
# Sample range for partial runs (set to None for all samples)
START_SAMPLE_IDX = None  # e.g., 0
END_SAMPLE_IDX = None    # e.g., 10


def main():
    """Run simulations for all Sobol samples."""

    if MPI_AVAILABLE:
        # MPI execution
        from mpi4py import MPI
        comm = MPI.COMM_WORLD
        rank = comm.Get_rank()
    else:
        # Serial execution
        rank = 0

    if rank == 0:
        print("=" * 70)
        print("PYWR-DRB SOBOL SENSITIVITY SIMULATIONS")
        print("=" * 70)

        # Check for pre-simulated releases if using trimmed model
        if USE_TRIMMED_MODEL:
            if not PRESIM_FILE.exists():
                print("\nERROR: Trimmed model requires pre-simulated releases.")
                print(f"  Expected file: {PRESIM_FILE}")
                print("\nPlease run first:")
                print("  python 00_generate_presimulated_releases.py")
                sys.exit(1)
            print(f"\nUsing TRIMMED MODEL (faster runtime)")
            print(f"  Pre-simulated releases: {PRESIM_FILE}")
        else:
            print(f"\nUsing FULL MODEL")

    # Load samples
    if rank == 0:
        print("\nLoading samples...")
        samples, problem = load_samples("sobol")

        n_total = len(samples)
        n_params = problem["num_vars"]

        print(f"  Total samples: {n_total}")
        print(f"  Parameters: {n_params}")
        print(f"  Simulation period: {START_DATE} to {END_DATE}")
        print(f"  Inflow type: {INFLOW_TYPE}")
        print(f"  Model type: {'TRIMMED' if USE_TRIMMED_MODEL else 'FULL'}")
    else:
        samples = None
        problem = None
        n_total = None
        n_params = None
    
    # Broadcast sample info to all ranks
    if MPI_AVAILABLE:
        samples = comm.bcast(samples, root=0)
        problem = comm.bcast(problem, root=0)
        n_total = comm.bcast(n_total, root=0)
        n_params = comm.bcast(n_params, root=0)
        comm.Barrier()

    # Determine sample range
    if START_SAMPLE_IDX is not None or END_SAMPLE_IDX is not None:
        start = START_SAMPLE_IDX if START_SAMPLE_IDX is not None else 0
        end = END_SAMPLE_IDX if END_SAMPLE_IDX is not None else n_total
        sample_ids = list(range(start, min(end, n_total)))
        print(f"  Sample range: {start} to {end}")
    else:
        sample_ids = None

    # Determine execution mode
    if not MPI_AVAILABLE:
        print("\n  Execution mode: SERIAL")

        # Run serial simulations
        print("\nStarting simulations...")
        results = run_simulations_serial(
            samples, problem,
            start_date=START_DATE,
            end_date=END_DATE,
            inflow_type=INFLOW_TYPE,
            sample_ids=sample_ids,
            use_trimmed_model=USE_TRIMMED_MODEL,
            presim_file=PRESIM_FILE
        )

        # Save results
        save_simulation_results(results)

    else:

        if rank == 0:
            print(f"\n  Execution mode: MPI PARALLEL")
            print(f"  MPI ranks: {comm.Get_size()}")

        # Run MPI parallel simulations
        results = run_parallel_simulations_mpi(
            samples, problem,
            start_date=START_DATE,
            end_date=END_DATE,
            inflow_type=INFLOW_TYPE,
            use_trimmed_model=USE_TRIMMED_MODEL,
            presim_file=PRESIM_FILE
        )

        # Save results (rank 0 only)
        if rank == 0 and results is not None:
            save_simulation_results(results)

    # Verification (rank 0 or serial)
    if not MPI_AVAILABLE or (MPI_AVAILABLE and MPI.COMM_WORLD.Get_rank() == 0):
        print("\nVerifying outputs...")
        verify_simulation_outputs()

        print("\n" + "=" * 70)
        print("SIMULATIONS COMPLETE")
        print("=" * 70)
        print(f"\nOutputs saved to: {SIMULATIONS_DIR}")
        print(f"Next step: Calculate metrics with 03_calculate_metrics.py")


if __name__ == "__main__":
    main()
